---
apiVersion: v2
name: prometheus
description: monitoring - metric collection tool
type: application
version: 1.0.14
sources:
  - https://prometheus-community.github.io/helm-charts
maintainers:
  - name: julian
    email: julian@diluz.io
dependencies:
  - name: kube-prometheus-stack
    # version: kube-prometheus-stack-72.6.4
    version: 81.4.3
    repository: https://prometheus-community.github.io/helm-charts
