---
vikunja:
  ingress:
    main:
      enabled: true
      hosts:
        - host: vikunja.cluster
          paths:
            - path: /

  persistence:
    data:
      enabled: true
      storageClass: "nfs-client"
      size: 1Gi
      mountPath: /data
  # configMaps:
  #   api-config:
  #     enabled: true
  #     data:
  #       config.yml:
  #         service:
  #           enableregistration: false
