---
vikunja:
  ingress:
    main:
      enabled: true
      hosts:
        - host: vikunja.cluster
          paths:
            - path: /
  postgresql:
    enabled: true
    global:
      security:
        allowInsecureImages: true
    image:
      registry: docker.io
      repository: library/postgres
      tag: "16-alpine"
    primary:
      persistence:
        enabled: true
        storageClass: "nfs-client"
        size: 5Gi
  # configMaps:
  #   api-config:
  #     enabled: true
  #     data:
  #       config.yml:
  #         service:
  #           enableregistration: false
