---
vikunja:
  ingress:
    main:
      enabled: true
      hosts:
        - host: vikunja.cluster
          paths:
            - path: /
  postgresql:
    enabled: true
    image:
      registry: registry.bitnami.com
      repository: bitnami/postgresql
      tag: "16-debian-12"
    primary:
      persistence:
        enabled: true
        storageClass: "nfs-client"
        size: 5Gi
  # configMaps:
  #   api-config:
  #     enabled: true
  #     data:
  #       config.yml:
  #         service:
  #           enableregistration: false
