---
vikunja:
  postgresql:
    enabled: true
    image:
      tag: latest
  vikunja:
    ingress:
      main:
        enabled: true
        hosts:
          - host: vikunja.cluster
            paths:
              - path: /
  # configMaps:
  #   api-config:
  #     enabled: true
  #     data:
  #       config.yml:
  #         service:
  #           enableregistration: false
