---
vikunja:
  ingress:
    main:
      enabled: true
      hosts:
        - host: vikunja.cluster
          paths:
            - path: /

  persistence:
    enabled: true
    storageClass: "nfs-client"
    size: 1Gi
  # configMaps:
  #   api-config:
  #     enabled: true
  #     data:
  #       config.yml:
  #         service:
  #           enableregistration: false
