---
apiVersion: v2
description: A chart for esphome in k3s
name: esphome
version: 1.0.3
maintainers:
  - name: julian
    email: julian@diluz.io
dependencies:
  - name: common
    version: 4.6.1
    repository: https://bjw-s-labs.github.io/helm-charts/
