image:
  repository: cloudflare/cloudflared
  tag: 2025.11.1
regions:
  - basePath: crmbs.net
    services:
      - subdomain: auth
        servicename: authentik-server
        namespace: authentik
        serviceport: 80
      - subdomain: argocd
        servicename: argocd-server
        namespace: argocd
        serviceport: 443
      # - subdomain: home
      #   servicename: home-assistant
      #   namespace: home-assistant
      #   serviceport: 80
      - subdomain: immich
        servicename: immich-server
        namespace: immich
        serviceport: 2283
      # - subdomain: jellyfin
      #   servicename: jellyfin
      #   namespace: jellyfin
      #   serviceport: 8096
      # - subdomain: status
      #   servicename: uptime-kuma
      #   namespace: uptime-kuma
      #   serviceport: 3001
      # - subdomain: vaultwarden
      #   servicename: vaultwarden
      #   namespace: vaultwarden
      #   serviceport: 80
      # - subdomain: obsidian
      #   servicename: obsidian
      #   namespace: obsidian
      #   serviceport: 80
      # - subdomain: mon
      #   servicename: monitoring-grafana
      #   namespace: monitoring
      #   serviceport: 80
